import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import LayoutClient from './LayoutClient' // new client wrapper
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Fiddunya-WalAkhirah',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutClient>
          <Navbar />
          <div className='container min-h-[83vh] max-w-[100vw] overflow-hidden'>
            {children}
          </div>
          <Footer />
        </LayoutClient>
      </body>
    </html>
  )
}
